name: Build fosAVG Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Node.js installieren
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Electron Builder installieren (global)
        run: npm install -g electron-builder

      - name: App bauen (Windows und macOS)
        run: |
          npx electron-builder --win --mac

      - name: Build-Artefakte hochladen
        uses: actions/upload-artifact@v3
        with:
          name: fosAVG-builds
          path: dist/
